### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by vpanfilov** [lppedd/bpmnio-typings#2]
Hello. Thanks for your effort. But there is no licensing information in this repository. Could you add a permissive license to it?

https://en.wikipedia.org/wiki/Permissive_software_license

**Comment by lppedd** [comment]
@vpanfilov there is no license because it was meant as a "backup" repo.
Do you need the license to integrate this in a commercial app?
Anyway you can grab the code, you don't even have to mention my name 😄
